site_name: Pre-U Robotic Workshop
theme:
  name: material
  icon: 
    logo: material/robot-excited
  favicon: img/favicon.svg
  custom_dir: overrides
  features:
    - toc.follow
    - toc.integrate
    - navigation.expand
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
site_dir: docs
docs_dir: src
extra_css:
  - css/main.css
  - css/reveal.css
  - css/reveal-themes/solarized.css
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/reveal.js
  - js/plugin/markdown/markdown.js
  - js/plugin/math/math.js
  - js/init-reveal.js
plugins: [ ]
extra:
  social: 
    - icon: fontawesome/solid/building
      link: https://university.sunway.edu.my/site
      name: School of Engineering and Technology
    - icon: fontawesome/brands/github
      link: https://ricwtk.github.io/
      name: Richard Wong
copyright: Prepared by <a href="https://ricwtk.github.io/" target="_blank">Richard Wong</a> for <a href="https://university.sunway.edu.my/set" taget="_blank">Sunway University, School of Engineering and Technology</a>
nav:
  - index.md
  - Basics: "basics.md"
  - Tutorial 1 LED: "tutorial-led-blinking.md"
  - Tutorial 2 Motor: "tutorial-motor.md"
  - Tutorial 3 Ultrasonic sensor: "tutorial-ultrasonic-sensor.md"
  - Tutorial 4 Micro servo: "tutorial-micro-servo.md"
  # - Tutorial 5 Infrared sensors: "tutorial-infrared-sensor.md"
  # - Tutorial 6 LED matrix: "tutorial-led-matrix.md"
  - Challenge 1: "challenge-hand.md"
  - Challenge 2: "challenge-obstacle-avoidance.md"
  # - Challenge 3: "challenge-line-following.md"